# RAG 系統配置文件

# Ollama 設定
ollama:
  base_url: "http://localhost:11434"
  model: "deepseek-r1:32b"
  timeout: 300
  max_tokens: 2048
  temperature: 0.1

# 向量嵌入設定
embeddings:
  model_name: "all-MiniLM-L6-v2"
  device: "cpu"  # 或 "cuda" 如果有GPU
  batch_size: 32
  max_length: 512

# 文本分塊設定
chunking:
  chunk_size: 1000
  chunk_overlap: 200
  separators: ["\n\n", "\n", "。", "；", "，", " "]

# 向量資料庫設定
vector_db:
  type: "chroma"  # 或 "faiss"
  persist_directory: "./vector_db"
  collection_name: "highway_traffic"
  distance_metric: "cosine"

# 檢索設定
retrieval:
  top_k: 5
  score_threshold: 0.7
  rerank: false

# 資料處理設定
data_processing:
  input_data_path: "../../data/Taiwan"
  highway1_file: "國道一號_整合資料.csv"
  highway3_file: "國道三號_整合資料.csv"
  output_dir: "./processed_data"
  
# 訓練設定
training:
  epochs: 5
  batch_size: 8
  learning_rate: 2e-5
  save_steps: 500
  eval_steps: 100
  warmup_steps: 100
  max_seq_length: 2048
  
# 評估設定
evaluation:
  test_size: 0.2
  metrics: ["accuracy", "bleu", "rouge"]
  
# 日誌設定
logging:
  level: "INFO"
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {message}"
  file: "rag_training.log"